### ISSUE TITLE
Openni structure sensor PATH

### ISSUE THREAD

**Issue by RajathSwaroop** [fangchangma/openni2_ros_wrapper#1]
Hi, I could'nt understand what is the path that needs to be set for the OpenNI2. I get an error that says could not find OpenNI.h and this header file is located at /usr/includes/openni2. If I set path as usr and let it find usr/includes/openni2 it gives me another set of errors.

**Comment by fangchangma** [comment]
How did you install OpenNI2? This wrapper is tested on the OpenNI2 from https://github.com/occipital/openni2, where you need to clone the repo and compile it locally
