### ISSUE TITLE
libDepthUtils.a libOpenNI2.so

### ISSUE THREAD

**Issue by CesMak** [fangchangma/openni2_ros_wrapper#2]
Hey there I changed in CMakeLists the following:

target_link_libraries (structure_sensor 
	${catkin_LIBRARIES} 
        #${OpenCV_LIBRARIES}
	libDepthUtils.a libOpenNI2.so
	#libDummyDevice.so libOniFile.so libPS1080.so libPSLink.so
)

I then get if building this error:

/usr/bin/ld: cannot find -lDepthUtils
collect2: error: ld returned 1 exit status
make[2]: *** [/hri/localdisk/markus/ros-cpp/devel/.private/openni2_ros_wrapper/lib/openni2_ros_wrapper/structure_sensor] Error 1
make[1]: *** [CMakeFiles/structure_sensor.dir/all] Error 2
make: *** [all] Error 2

PS I always get this error I just changed CMake Lists to see it more clearly ......
Do I somehow have to install libDepth Util ??

**Comment by CesMak** [comment]
solved my problem:

need to change:


link_directories ("${OPENNI2_PATH}/Bin/x64-Release")
link_directories ("${OPENNI2_PATH}/Bin/x64-Release/OpenNI2/Drivers") 

in CMakeLists.txt

**Comment by fangchangma** [comment]
Thanks. I'll put this in the README. Closing the ticket.
