### ISSUE TITLE
How to visualize sensor data over ROS?

### ISSUE THREAD

**Issue by xoxota99** [fangchangma/openni2_ros_wrapper#3]
Any recommendations for a visualizer to show the depth data that's being published?

**Comment by fangchangma** [comment]
I haven't worked on this for a while, but the ROS builtin viewer should work fine. Launch `image_view` with the following command, and then select the corresponding topics.
```
rosrun image_view image_view
```

**Comment by xoxota99** [comment]
Thanks!
